INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0001', 'Enrollado de Jamón y Queso "El Cedro"', 'Comidas', '1 und', '50', '8.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0002', 'Enrollado de Lechón "El Cedro"', 'Comidas', '1 und', '50', '8.50');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0003', 'Enrollado de Pollo "El Cedro"', 'Comidas', '1 und', '50', '8.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0004', 'Pizzas Familiar Americana Tambo', 'Comidas', '2 und Combo', '50', '25.80');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0005', 'Pizzas Familiar Carnivora Tambo', 'Comidas', '2 und Combo', '50', '25.85');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0006', 'Pizzas Familiar Hawaiana Tambo', 'Comidas', '2 und Combo', '50', '27.80');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0007', 'Pizzas Familiar Pepperoni Tambo', 'Comidas', '2 und Combo', '50', '29.80');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0008', 'Empanadas de Pollo + Coca Cola', 'Comidas', '6 empanadas + Coca Cola 1 Lt.', '50', '11.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0009', 'Hamburguesa de Res + Inka Cola', 'Comidas', '2 hamburguesas + Inka Cola 1 Lt.', '50', '7.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0010', 'Hamburguesa Parrillera + Coca Cola', 'Comidas', '2 hamburguesas + Coca Cola 1 Lt.', '50', '16.40');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0011', 'Empandas Mixtas', 'Comidas', '5 empanadas mixtas', '50', '8.50');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0012', 'Torta Selva Negra', 'Comidas', '2 trozos de torta Selva Negra', '50', '5.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0013', 'Arroz Chaufa Tugou', 'Comidas', '1 und', '50', '3.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0014', 'Causa Rellena Tugou', 'Comidas', '1 und', '50', '3.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0015', 'Pollo Rostizado + Inka Cola', 'Comidas', '1 pollo rostizado + Inka Cola 1 Lt.', '50', '24.50');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0016', 'Cerveza Tres Cruces Lager', 'Bebidas Alcoholicas', '1 botella x 650 ml.', '50', '5.50');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0017', 'Corona Tropical Frutos Rojos', 'Bebidas Alcoholicas', '1 lata x 355 ml.', '50', '6.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0018', 'Smirmoff Ice Green Apple', 'Bebidas Alcoholicas', '1 lata x 350 ml.', '50', '6.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0019', 'Four Loko Gold', 'Bebidas Alcoholicas', '1 lata x 473 ml.', '50', '11.00');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0020', 'Mikes Hard Lemonade', 'Bebidas Alcoholicas', '1 lata x 355 ml.', '50', '19.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0021', 'Cerveza Pilsen Callao Six Pack ', 'Bebidas Alcoholicas', '6 latas x 355 ml.', '50', '21.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0022', 'Cerveza Corona Six Pack ', 'Bebidas Alcoholicas', '6 botellas x 355 ml.', '50', '28.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0023', 'Cerveza Corona Six Pack ', 'Bebidas Alcoholicas', '6 latas x 355 ml.', '50', '21.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0024', 'Cerveza Pilsen Callao Six Pack ', 'Bebidas Alcoholicas', '6 latas x 473 ml.', '50', '22.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0025', 'Cerveza Tres Cruces Six Pack', 'Bebidas Alcoholicas', '6 botellas x 355 ml.', '50', '19.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0026', 'Cerveza Budweiser Six Pack ', 'Bebidas Alcoholicas', '6 botellas x 343 ml.', '50', '21.90');
INSERT INTO PRODUCTO (Codigo, Producto, Categoria, Descripcion, Stock, Precio) VALUES ('P0027', 'Cerveza Cristal Six Pack ', 'Bebidas Alcoholicas', '6 latas x 355 ml.', '50', '17.90');